### ISSUE TITLE
A Question in regards to the TreeKEM test

### ISSUE THREAD

**Issue by Aurvandill** [mlswg/mls-implementations#177]
In the Test Description for the TreeKEM tests there is the following written.

* For each entry in `update_paths`:
  * For each leaf node index `j != i` for which the leaf node is not blank:
    * Process `update_path` using `private_leaf[j]`
    * Verify that `path_secrets[j]` is the decrypted path secret
    * Verify that `commit_secret` is the resulting commit secret

is `i` the sender leaf index?

with best regards
Aurvandill

**Comment by RonPeters** [comment]
Hi @Aurvandill, I'm in the middle of implementing the TreeKEM tests. `i` is the sender leaf index, and `j` is the recipient leaf index

**Comment by Aurvandill** [comment]
thanks for the answer :)
