### ISSUE TITLE
Key Packages in Passive Client Test Vectors are expired

### ISSUE THREAD

**Issue by Traderjoe95** [mlswg/mls-implementations#181]
I just noticed when running my test suite that the key packages in the [passive-client-random.json](https://github.com/mlswg/mls-implementations/blob/main/test-vectors/passive-client-random.json) and [passive-client-handling-commit.json](https://github.com/mlswg/mls-implementations/blob/main/test-vectors/passive-client-handling-commit.json) test vectors have expired this afternoon and are now rejected by my implementation.

Could you please take care to update them?

**Comment by bifurcation** [comment]
I'm a little split on this.  Seems like we're balancing three mutually incompatible objectives:

1. Have the tests pass
2. Check that implementations correctly check lifetimes
3. Avoid having to repeatedly update the test vectors

Personally, I would probably sacrifice (2), and just give the KeyPackages the perpetual `(0x0000000000000000, 0xffffffffffffffff)` lifetime.

@mulmarta you're the one with the ability to generate these vectors, what do you think?

**Comment by mulmarta** [comment]
I agree, I'll put up a PR with test vectors for the perpetual lifetime.

**Comment by emersion** [comment]
With this PR, the Ed25519 private keys in KeyPackages have a size of 64 bytes instead of the expected 32 bytes.

Truncating to 32 bytes makes the tests pass for me.

**Comment by LukaJCB** [comment]
It looks like there are still some leaf nodes in the `passive-client-welcome.json` that have expired KeyPackages. Should those be updated as well? The spec says this:

```
If instead the LeafNode appears in a message being received by the client, e.g., a Proposal, a Commit, or a ratchet tree of the group the client is joining, it is RECOMMENDED that the client verifies that the current time is within the range of the lifetime field. (This check is not mandatory because the LeafNode might have expired in the time between when the message was sent and when it was received.)
```

So it's not mandatory but it would still be great to change this, since it's RECOMMENDED that it be verified
