### ISSUE TITLE
Add a "basic crypto functions" test vector

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-implementations#64]
Before diving into the key schedule / encryption tests, it would be good to enable folks to verify that things like `ExpandWithLabel` and `DeriveSecret` are working properly.  This should just be a few specific values, say one per hash / ciphersuite.

**Comment by TWal** [comment]
Maybe testing `SignWithLabel` / `VerifyWithLabel` and `EncryptWithLabel` / `DecryptWithLabel` alongside would be useful!
